name: Build add-on

on:
  pull_request:
    branches: ["master"]
  release:
    types: ["published"]
  push:
    branches: ["master"]

jobs:
  build:
    name: Build add-on
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v2

    - name: Login to DockerHub
      if: github.event_name == 'release'
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Set build arguments
      if: github.event_name != 'release'
      run: echo "BUILD_ARGS=--test" >> $GITHUB_ENV

    - name: Build add-on
      uses: home-assistant/builder@2020.10.0
      with:
        args: |
          $BUILD_ARGS \
          --all \
          --target /data/netdaemon
